// Mock data for products
export const categories = [
  { id: 1, name: 'Áo thun', icon: 'fa-tshirt' },
  { id: 2, name: 'Quần', icon: 'fa-shopping-bag' },
  { id: 3, name: 'Giày', icon: 'fa-shoe-prints' },
  { id: 4, name: 'Phụ kiện', icon: 'fa-glasses' },
  { id: 5, name: 'Đồng hồ', icon: 'fa-clock' },
  { id: 6, name: 'Túi xách', icon: 'fa-briefcase' },
];

export const products = [
  {
    id: 1,
    name: 'Áo thun basic màu đen',
    price: 299000,
    originalPrice: 399000,
    image: 'https://via.placeholder.com/400x400?text=Ao+Thun+Den',
    images: [
      'https://via.placeholder.com/400x400?text=Ao+Thun+Den+1',
      'https://via.placeholder.com/400x400?text=Ao+Thun+Den+2',
      'https://via.placeholder.com/400x400?text=Ao+Thun+Den+3',
    ],
    category: 'Áo thun',
    categoryId: 1,
    description: 'Áo thun chất lượng cao, thoáng mát, phù hợp mọi lứa tuổi',
    inStock: true,
    variants: {
      colors: ['Đen', 'Trắng', 'Xám'],
      sizes: ['S', 'M', 'L', 'XL'],
    },
    rating: 4.5,
    reviews: 128,
    featured: true,
    bestseller: true,
  },
  {
    id: 2,
    name: 'Quần jeans slim fit',
    price: 599000,
    originalPrice: 799000,
    image: 'https://via.placeholder.com/400x400?text=Quan+Jeans',
    images: [
      'https://via.placeholder.com/400x400?text=Quan+Jeans+1',
      'https://via.placeholder.com/400x400?text=Quan+Jeans+2',
    ],
    category: 'Quần',
    categoryId: 2,
    description: 'Quần jeans form slim, chất liệu denim cao cấp',
    inStock: true,
    variants: {
      colors: ['Xanh đậm', 'Xanh nhạt'],
      sizes: ['28', '30', '32', '34'],
    },
    rating: 4.8,
    reviews: 256,
    featured: true,
    bestseller: true,
  },
  {
    id: 3,
    name: 'Giày thể thao chạy bộ',
    price: 1299000,
    originalPrice: 1599000,
    image: 'https://via.placeholder.com/400x400?text=Giay+The+Thao',
    images: [
      'https://via.placeholder.com/400x400?text=Giay+The+Thao+1',
      'https://via.placeholder.com/400x400?text=Giay+The+Thao+2',
      'https://via.placeholder.com/400x400?text=Giay+The+Thao+3',
    ],
    category: 'Giày',
    categoryId: 3,
    description: 'Giày thể thao êm ái, hỗ trợ tốt cho chạy bộ',
    inStock: true,
    variants: {
      colors: ['Đen', 'Trắng', 'Xanh'],
      sizes: ['39', '40', '41', '42', '43'],
    },
    rating: 4.7,
    reviews: 189,
    featured: true,
    bestseller: false,
  },
  {
    id: 4,
    name: 'Kính mát thời trang',
    price: 399000,
    originalPrice: 599000,
    image: 'https://via.placeholder.com/400x400?text=Kinng+Mat',
    images: [
      'https://via.placeholder.com/400x400?text=Kinng+Mat+1',
      'https://via.placeholder.com/400x400?text=Kinng+Mat+2',
    ],
    category: 'Phụ kiện',
    categoryId: 4,
    description: 'Kính mát chống tia UV, thiết kế thời trang',
    inStock: true,
    variants: {
      colors: ['Đen', 'Nâu', 'Xanh'],
      sizes: ['Một size'],
    },
    rating: 4.6,
    reviews: 95,
    featured: false,
    bestseller: false,
  },
  {
    id: 5,
    name: 'Đồng hồ thông minh',
    price: 2999000,
    originalPrice: 3999000,
    image: 'https://via.placeholder.com/400x400?text=Dong+Ho+Thong+Minh',
    images: [
      'https://via.placeholder.com/400x400?text=Dong+Ho+Thong+Minh+1',
      'https://via.placeholder.com/400x400?text=Dong+Ho+Thong+Minh+2',
    ],
    category: 'Đồng hồ',
    categoryId: 5,
    description: 'Đồng hồ thông minh với nhiều tính năng hiện đại',
    inStock: true,
    variants: {
      colors: ['Đen', 'Bạc'],
      sizes: ['Một size'],
    },
    rating: 4.9,
    reviews: 342,
    featured: true,
    bestseller: true,
  },
  {
    id: 6,
    name: 'Túi xách da thật',
    price: 899000,
    originalPrice: 1199000,
    image: 'https://via.placeholder.com/400x400?text=Tui+Xach+Da',
    images: [
      'https://via.placeholder.com/400x400?text=Tui+Xach+Da+1',
      'https://via.placeholder.com/400x400?text=Tui+Xach+Da+2',
    ],
    category: 'Túi xách',
    categoryId: 6,
    description: 'Túi xách da thật, thiết kế sang trọng',
    inStock: true,
    variants: {
      colors: ['Nâu', 'Đen'],
      sizes: ['Một size'],
    },
    rating: 4.7,
    reviews: 167,
    featured: false,
    bestseller: true,
  },
  {
    id: 7,
    name: 'Áo thun cổ tròn',
    price: 249000,
    originalPrice: 349000,
    image: 'https://via.placeholder.com/400x400?text=Ao+Thun+Co+Tron',
    images: [
      'https://via.placeholder.com/400x400?text=Ao+Thun+Co+Tron+1',
    ],
    category: 'Áo thun',
    categoryId: 1,
    description: 'Áo thun cổ tròn thoải mái, dễ phối đồ',
    inStock: true,
    variants: {
      colors: ['Trắng', 'Xanh', 'Hồng'],
      sizes: ['S', 'M', 'L'],
    },
    rating: 4.4,
    reviews: 89,
    featured: false,
    bestseller: false,
  },
  {
    id: 8,
    name: 'Quần short thể thao',
    price: 349000,
    originalPrice: 499000,
    image: 'https://via.placeholder.com/400x400?text=Quan+Short',
    images: [
      'https://via.placeholder.com/400x400?text=Quan+Short+1',
      'https://via.placeholder.com/400x400?text=Quan+Short+2',
    ],
    category: 'Quần',
    categoryId: 2,
    description: 'Quần short thể thao thoáng mát, co giãn tốt',
    inStock: true,
    variants: {
      colors: ['Đen', 'Xám', 'Xanh'],
      sizes: ['S', 'M', 'L', 'XL'],
    },
    rating: 4.5,
    reviews: 134,
    featured: false,
    bestseller: false,
  },
];

// Mock orders
export const mockOrders = [
  {
    id: 'ORD001',
    date: '2024-01-15',
    status: 'completed',
    items: [
      {
        id: 1,
        name: 'Áo thun basic màu đen',
        price: 299000,
        quantity: 2,
        variant: { color: 'Đen', size: 'M' },
        image: 'https://via.placeholder.com/100x100?text=Ao+Thun',
      },
    ],
    total: 598000,
    shipping: {
      name: 'Nguyễn Văn A',
      phone: '0901234567',
      email: 'nguyenvana@email.com',
      address: '123 Đường ABC, Quận 1, TP.HCM',
    },
  },
  {
    id: 'ORD002',
    date: '2024-01-20',
    status: 'delivering',
    items: [
      {
        id: 3,
        name: 'Giày thể thao chạy bộ',
        price: 1299000,
        quantity: 1,
        variant: { color: 'Đen', size: '42' },
        image: 'https://via.placeholder.com/100x100?text=Giay',
      },
    ],
    total: 1299000,
    shipping: {
      name: 'Nguyễn Văn A',
      phone: '0901234567',
      email: 'nguyenvana@email.com',
      address: '123 Đường ABC, Quận 1, TP.HCM',
    },
  },
  {
    id: 'ORD003',
    date: '2024-01-25',
    status: 'processing',
    items: [
      {
        id: 5,
        name: 'Đồng hồ thông minh',
        price: 2999000,
        quantity: 1,
        variant: { color: 'Đen' },
        image: 'https://via.placeholder.com/100x100?text=Dong+Ho',
      },
    ],
    total: 2999000,
    shipping: {
      name: 'Nguyễn Văn A',
      phone: '0901234567',
      email: 'nguyenvana@email.com',
      address: '123 Đường ABC, Quận 1, TP.HCM',
    },
  },
];

export const orderStatuses = {
  pending: { label: 'Đã đặt', color: 'warning' },
  processing: { label: 'Đang xử lý', color: 'info' },
  delivering: { label: 'Đang giao', color: 'primary' },
  completed: { label: 'Hoàn thành', color: 'success' },
  cancelled: { label: 'Đã hủy', color: 'danger' },
};

